version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # Root directory where requirements.txt is located
    schedule:
      interval: "daily"  # Changed from weekly to daily to trigger update
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"  # Only update direct dependencies
